name: Rust

on:
  push:
    branches: [ "feat/#3216" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: "packages/renderer -> target"
    - name: Install
      run: pnpm install --frozen-lockfile
    - name: Build
      run: cd packages/renderer && node build.mjs

